// layout.tsx
import { ReactNode } from "react";
import "../globals.css";
import type { Metadata } from "next";
import NavBar from '@/components/shared/NavBar'
import LeftSideBar from "@/components/shared/LeftSideBar";

export const metadata: Metadata = {
  title: "Connexion",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }: { children: ReactNode }) {
  return (
    <div className="min-h-screen flex flex-col">
      {/* NavBar at the top */}
      <NavBar />

      {/* Flex container for sidebar + content */}
      <div className="flex flex-1">
        {/* LeftSideBar */}
        <LeftSideBar />

        {/* Main content area */}
        <div className="flex-1 overflow-y-auto">
          {children}
        </div>
      </div>
    </div>
  );
}