// layout.tsx
import { ReactNode } from "react";
import "../globals.css";
import type { Metadata } from "next";

interface RootLayoutProps {
    children: ReactNode;
}

export const metadata: Metadata = {
    title: "Login / Sign-up",
    description: "Generated by create next app",
  };

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <div className="min-h-screen bg-black">
            {children}
        </div>
    );
}
