// layout.tsx
import { ReactNode } from "react";
import "../globals.css";
import type { Metadata } from "next";
import Authbar from "@/components/shared/Authbar";

export const metadata: Metadata = {
    title: "Login | Connexion",
    description: "Generated by create next app",
  };

export default function AuthLayout({ children }: { children: ReactNode }) {
    return (
      <div>
        {/* Auth-specific layout components like headers or footers */}
        <Authbar />
        {children}
      </div>
    );
  }