// layout.tsx
import { ReactNode } from "react";
import "../globals.css";
import type { Metadata } from "next";
import { Users, StickyNote, Handshake, Home } from 'lucide-react';
import Link from 'next/link';

export const metadata: Metadata = {
  title: "Connexion | Admin Portal",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }: { children: ReactNode }) {

  const adminControls = [
    { icon: Home, label: "Home", href: "/admin" },
    { icon: Users, label: "Users", href: "/admin/users" },
    { icon: StickyNote, label: "Posts", href: "/admin/posts" },
    { icon: Handshake, label: "Communities", href: "/admin/communities" },
  ]

  

  return (
    <section>
      <main className='h-screen w-full flex'>
        {children}
      </main>
    </section>
  );
}